In [1]:
#Imports
import sys,glob,os
import numpy as np
import cPickle as pickle
sys.path.append(r'C:\Data\Alistair\code\python-functions\python-functions-library')
import TadImagingAnalysis as tia
import matplotlib.pylab as plt

In [2]:
#Get file paths

master_folder = r'D:\Bogdan\HCT16_6hauxin_noAB-2col_7_1_2018'
folders = [folder for folder in glob.glob(master_folder+os.sep+'*') 
           if ('R' in os.path.basename(folder) or 'P' in os.path.basename(folder) and 'H' in os.path.basename(folder))]
#folders = [folder for folder in glob.glob(master_folder+os.sep+'*') 
#           if ('X' in os.path.basename(folder) or os.path.basename(folder) in['H1R9']) and os.path.isdir(folder)]
def get_hybe(folder):
    #this sorts by hybes.
    try: return int(os.path.basename(folder).split('H')[-1].split('R')[0])
    #try: return int(os.path.basename(folder).split('R')[-1])
    except: return np.inf
folders = np.array(folders)[np.argsort(map(get_hybe,folders))]
fovs = map(os.path.basename,glob.glob(folders[0]+os.sep+'*.dax'))
analysis_folder = master_folder+os.sep+r'Analysis'

#Load positions of selected chroms
dic = pickle.load(open(analysis_folder+os.sep+'Selected_Spot.pkl','r'))
reload(tia)
chr_pts = tia.partition_map(dic['coords'],dic['class_ids'])
fov_ids = np.unique(dic['class_ids'])

im_beads_repair = pickle.load(open(analysis_folder+os.sep+'im_beads_repair1.pkl','rb'))
im_cy5_repair = pickle.load(open(analysis_folder+os.sep+'im_cy5_repair1.pkl','rb'))
im_cy7_repair = pickle.load(open(analysis_folder+os.sep+'im_cy7_repair1.pkl','rb'))


folders = [folder for folder in folders if os.path.exists(folder+os.sep+fovs[0])]
folders

['D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H1R1,R2',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H2R3,R4',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H3R5,R6',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H4R7,R8',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H5R9,R10',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H6R11,R12',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H7R13,R14',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H8R15,R16',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H9R17,R18',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H10R19,R20',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H11R21,R22',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H12R23,R24',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H13R25,R26',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H14R27,R28',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H15R29,R30',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_2018\\H16R31,R32',
 'D:\\Bogdan\\HCT16_6hauxin_noAB-2col_7_1_

In [4]:
#def to_2tags(tag,single_dic={'P41':'cy5','P6':'cy7'},inverted=['R49','R53','R54']):
def to_2tags(tag,single_dic={'P1':'cy7','R83':'cy5'},inverted=[]):
    hybe = tag.split('R')[0].split('P')[0]
    rest = tag[len(hybe):]
    cols = ['cy5','cy7']
    for stag in single_dic.keys():
        if stag==rest:
            icol = cols.index(single_dic[stag])*2-1
            return [tag+'_blank',tag][::icol]
    icol = 1
    for tg in inverted:
        if tg in tag:
            icol=-1
    tags2 = [hybe+rst for rst in rest.split(',')]
    return tags2[::icol]
map(to_2tags,map(os.path.basename,folders))

[['H1R1', 'H1R2'],
 ['H2R3', 'H2R4'],
 ['H3R5', 'H3R6'],
 ['H4R7', 'H4R8'],
 ['H5R9', 'H5R10'],
 ['H6R11', 'H6R12'],
 ['H7R13', 'H7R14'],
 ['H8R15', 'H8R16'],
 ['H9R17', 'H9R18'],
 ['H10R19', 'H10R20'],
 ['H11R21', 'H11R22'],
 ['H12R23', 'H12R24'],
 ['H13R25', 'H13R26'],
 ['H14R27', 'H14R28'],
 ['H15R29', 'H15R30'],
 ['H16R31', 'H16R32'],
 ['H17R33', 'H17R34'],
 ['H18R35', 'H18R36'],
 ['H19R37', 'H19R38'],
 ['H20R39', 'H20R40'],
 ['H21R41', 'H21R42'],
 ['H22R43', 'H22R44'],
 ['H23R45', 'H23R46'],
 ['H24R47', 'H24R48'],
 ['H25R49', 'H25R50'],
 ['H26R51', 'H26R52'],
 ['H27R53', 'H27R54'],
 ['H28R55', 'H28R56'],
 ['H29R57', 'H29R58'],
 ['H30R59', 'H30R60'],
 ['H31R61', 'H31R62'],
 ['H32R63', 'H32R64'],
 ['H33R65', 'H33R66'],
 ['H34R67', 'H34R68'],
 ['H35R69', 'H35R70'],
 ['H36R71', 'H36R72'],
 ['H37R73', 'H37R74'],
 ['H38R75', 'H38R76'],
 ['H39R77', 'H39R78']]

In [5]:
#folders = ['D:\\Bogdan\\A549_SI13Ext_D_3_26_2018\\H1R9','D:\\Bogdan\\A549_SI13Ext_D_3_26_2018\\H106X53']
reload(tia)

##where to save
analysis_folder = master_folder+os.sep+r'AnalysisTemp'
if not os.path.exists(analysis_folder):
    os.makedirs(analysis_folder)

###paramaters
overwrite=False

#drift paramaters
ref=0 #drift reference hybe
sz_ex=80 #the effective size of the cube to do drift correction
hseed_beads=150 # The minimum bead height (prefitting)
nbeads = 100 # The maximum number of beads
force_drift=False
#brightness cutoffs
low_limit=150 #the minimum prefitting signal height
bad_low_limit = 75
bad_tags = []#['R53']
prefered_limit=300 #the initial try of prefitting signal height
#distance cutoffs
cutoff_window=20 #fitted points within this distance will be reported
cutoff_chr=10 #if no prefered brightness points are detected within this distance, then include low brightness ones
from scipy.spatial.distance import cdist

#iterate through good fields of view
ind=0
folders_keep_base = folders[:]
folders_keep = list(folders_keep_base)
#itterate through fields of view
for ind in range(len(fov_ids))[:]:#[21]:#
    ##limit the folder hybes
    fov_id = fov_ids[ind]
    file_=fovs[fov_id]
    chr_pts_ = chr_pts[ind] #positions of the selected centers of chromosomes in reference frame.
    chr_pts_ = np.array(chr_pts_)[:,::-1]#zxy coords of chromosomes already in the right position
    
    #Decide where to save the candidate positions of the hybe
    fl_cands = analysis_folder+os.sep+file_.replace('.dax','__current_cand.pkl')#file where it save candidates
    fl_cor = analysis_folder+os.sep+file_.replace('.dax','__current_cor_v9.pkl')
    print fl_cands
    candid_spot={}
    
    #simplify folder and keep only what has not been analysed except for one reference.
    tags = [os.path.basename(folder) for folder in folders_keep_base]
    start=0
    if os.path.exists(fl_cands) and not overwrite:
        candid_spot = pickle.load(open(fl_cands,'rb'))
        tags_existing = []
        for key in candid_spot.keys():
            cand_dic_0 = candid_spot[key][0]
            tags_existing.extend(cand_dic_0.keys())
        tags_existing = np.unique(tags_existing)
        keep = np.array([tag not in tags_existing for tag in tags])
        folders_in_common = [folder for tag,folder in zip(tags,folders_keep) if tag in tags_existing]
        folders_keep = [folders_in_common[0]]+list(np.array(folders_keep_base)[keep])
        start = 1
    #tags = ['H2R10','H59R58','H60R59','H61R60','H62R61','H63R62','H64R63','H65R64','H66R65']
    #tags=['H2R10', 'H67P10', 'H68P53']
    #folders_keep = [os.path.dirname(folders_keep[0])+os.sep+tag for tag in tags]
    
    tags = [os.path.basename(folder) for folder in folders_keep]
    print tags
    #load data (memory mapping)
    ims_beads=[]
    ims_cy5=[]
    ims_cy7=[]
    tags = []
    for folder in folders_keep:
        file__= folder+os.sep+file_
        if os.path.exists(file__):
            #print file__
            tags.append(os.path.basename(folder))
            im = tia.DaxReader(file__).loadMap()
            ims_beads += [im[10:-10][2::3]]
            ims_cy5 += [im[10:-10][1::3]]
            ims_cy7 += [im[10:-10][0::3]]
    #compute the drift for the field of view
    if len(ims_beads)>1:
        #txyz_both,overwrite = tia.get_STD_beaddrift_v2(ims_beads,tags,sz_ex=sz_ex,hseed=hseed_beads,nseed=nbeads,ref=None,force=force_drift,save_file=fl_cor)
        txyz_both,_ = tia.get_STD_beaddrift(ims_beads,sz_ex=sz_ex,hseed=hseed_beads,nseed=nbeads,ref=None,force=force_drift,save_file=fl_cor)
        txyz = tia.simplify_txyz(txyz_both)
        txyz = np.array(txyz)-[txyz[ref]]

    #iterate through folders
    for iim in range(len(ims_cy5))[start:]:#skip the reference
        #iim specific vars
        tag = tags[iim]
        txyz_ = txyz[iim]
        print to_2tags(tag)
        #correct for illumination
        #cy5
        im=np.array(ims_cy5[iim],dtype=float)/im_cy5_repair*np.median(im_cy5_repair)
        tia.update_candid_spot(im,low_limit,prefered_limit,chr_pts_,txyz_,to_2tags(tag)[0],
                       cutoff_window,cutoff_chr,candid_spot,fl_cands)
        #cy7
        im=np.array(ims_cy7[iim],dtype=float)/im_cy7_repair*np.median(im_cy7_repair)
        tia.update_candid_spot(im,low_limit,prefered_limit,chr_pts_,txyz_,to_2tags(tag)[-1],
                       cutoff_window,cutoff_chr,candid_spot,fl_cands)

D:\Bogdan\HCT16_6hauxin_noAB-2col_7_1_2018\AnalysisTemp\Conv_zscan_00__current_cand.pkl
['H1R1,R2', 'H2R3,R4', 'H3R5,R6', 'H4R7,R8', 'H5R9,R10', 'H6R11,R12', 'H7R13,R14', 'H8R15,R16', 'H9R17,R18', 'H10R19,R20', 'H11R21,R22', 'H12R23,R24', 'H13R25,R26', 'H14R27,R28', 'H15R29,R30', 'H16R31,R32', 'H17R33,R34', 'H18R35,R36', 'H19R37,R38', 'H20R39,R40', 'H21R41,R42', 'H22R43,R44', 'H23R45,R46', 'H24R47,R48', 'H25R49,R50', 'H26R51,R52', 'H27R53,R54', 'H28R55,R56', 'H29R57,R58', 'H30R59,R60', 'H31R61,R62', 'H32R63,R64', 'H33R65,R66', 'H34R67,R68', 'H35R69,R70', 'H36R71,R72', 'H37R73,R74', 'H38R75,R76', 'H39R77,R78']


C:\Users\Storm6\Anaconda2\lib\site-packages\scipy\optimize\minpack.py:427: RuntimeWarning: Number of calls to function has reached maxfev = 1200.
  warnings.warn(errors[info][0], RuntimeWarning)


Aligning 0
[ -3.13013163  19.71102063 -14.76443644] [ -2.60339537  19.60885652 -14.62391904] 44 25
Suspecting failure.
[array([ -3.12730923,  19.72263036, -14.67888723]), array([ -3.13013163,  19.71102063, -14.76443644])]
Aligning 1
[ -4.43743549  17.89289934 -13.48905109] [ -4.57042094  17.73899595 -13.55854466] 42 29
Aligning 2
[ -2.0513969   18.46547823 -11.6965114 ] [ -1.87337556  18.3637279  -11.68663338] 45 43
Aligning 3
[ -4.58583636  15.78412907 -10.45076443] [ -4.692263    15.73248136 -10.51002344] 48 34
Aligning 4
[ -4.58068958  14.62004985  -9.7492243 ] [ -4.75526153  14.4733473   -9.69158944] 54 36
Aligning 5
[ -4.64831969  11.54851678  -8.47737627] [ -4.774947    11.47383792  -8.49604404] 55 40
Aligning 6
[ -4.70940187  12.30859497  -7.54379329] [ -4.90365022  12.2676696   -7.48290187] 57 33
Aligning 7
[ -4.74227322  11.30731404  -6.81766083] [ -4.91759801  11.224788    -6.77235808] 59 39
Aligning 8
[ -4.76749076  10.46515925  -6.34405651] [ -4.77951667  10.44693432  -6.33

In [303]:
pickle.load(open(r'D:\Bogdan\A549_SI13Ext_D_3_26_2018\Analysis5\Conv_zscan_21__current_cor_v2X.pkl','rb'))

{'H1R9': array([[-0.18844849, -0.05478291, -0.09958932],
        [ 0.18844849,  0.05478291,  0.09958932]]),
 'H20R1': array([[-0.17371287, -0.41107573, -0.87147261],
        [ 0.03868514, -0.39550646, -0.85415891]]),
 'H21R2': array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]),
 'H22R3': array([[-0.15541841, -0.30854442, -0.35422327],
        [ 0.00431397, -0.33717363, -0.33183036]]),
 'H23R4': array([[-0.19498527, -0.98761648, -0.89142904],
        [ 0.02800608, -0.98408981, -0.85627313]]),
 'H24R5': array([[-0.35025263, -1.01278085, -0.94332314],
        [ 0.09296144, -0.99196635, -0.92722957]]),
 'H25R6': array([[-0.26168647, -0.6496551 , -1.05770227],
        [ 0.05097884, -0.65355239, -1.04699885]]),
 'H26R7': array([[-0.12782036,  1.81066072,  0.48889034],
        [ 0.16884796,  1.82515572,  0.45945736]]),
 'H27R8': array([[-0.05696053,  1.27727627,  1.17395812],
        [ 0.18666928,  1.26957657,  1.1622168 ]]),
 'H2R10': array([[-0.46473186,  0.15457567, -1.18363941],
        [-

In [ ]:
Aligning 0
[-0.36045557 -1.91663039 -1.79808793] [-0.10502739 -1.75878778 -1.6700326 ] 68 68
Aligning 1
[-0.46473186  0.15457567 -1.18363941] [-0.17651543  0.32043216 -1.00927856] 67 67
Aligning 2
[-0.3536681  -0.53456773 -1.38518558] [-0.19795125 -0.35940894 -1.22554202] 68 68
Aligning 3
[-0.26828651 -0.2317284  -1.46064739] [-0.12236094 -0.07743284 -1.26272727] 69 69

In [299]:
force_drift

True

In [298]:
tags

['H1R9',
 'H2R10',
 'H3R11',
 'H4R12',
 'H5R13',
 'H6R14',
 'H20R1',
 'H21R2',
 'H22R3',
 'H23R4',
 'H24R5',
 'H25R6',
 'H26R7',
 'H27R8']

In [284]:
"""
folders_keep = folders[:]
ind=0
fov_id = fov_ids[ind]
im_means=[]
file_=fovs[fov_id]
print file_
ims_cy5,ims_beads,names=[],[],[]
for folder in folders_keep:
    file__= folder+os.sep+file_
    if os.path.exists(file__):
        names+=[os.path.basename(folder)]
        im = tia.DaxReader(file__).loadMap()
        ims_beads += [im[2::2][5:-5]]#/im_beads_repair*np.median(im_beads_repair)]
        ims_cy5 += [im[1::2][5:-5]]#/im_cy5_repair*np.median(im_cy5_repair)]
"""
sz_ex = 75
im = ims_beads[0]
coord_sel1 = np.array(im.shape)/2
im_sm = tia.grab_block(im,coord_sel1,[sz_ex]*3)
#cents1 = get_STD_centers(im_sm)
centers1 = tia.get_seed_points_base(im_sm,gfilt_size=0.75,filt_size=3,th_seed=hseed_beads,hot_pix_th=5)
pfits1 = tia.fit_seed_points_base_fast(im_sm,centers1,width_z=1.,width_xy=1.,radius_fit=5,n_max_iter=10,max_dist_th=0.25)
x,y,z = pfits1[:,1:4].T
plt.figure()
plt.plot(z,y,'rx')
plt.imshow(np.max(im_sm,0),interpolation='nearest',cmap='gray')

im = ims_beads[len(ims_beads)/2]
coord_sel1 = np.array(im.shape)/2
im_sm = tia.grab_block(im,coord_sel1,[sz_ex]*3)
#cents1 = get_STD_centers(im_sm)
centers2 = tia.get_seed_points_base(im_sm,gfilt_size=0.75,filt_size=3,th_seed=hseed_beads,hot_pix_th=5)
pfits2 = tia.fit_seed_points_base_fast(im_sm,centers2,width_z=1.8*1.5/2.,width_xy=1.,radius_fit=5,n_max_iter=10,max_dist_th=0.25)
x,y,z = pfits2[:,1:4].T
plt.figure()
plt.plot(z,y,'rx')
plt.imshow(np.max(im_sm,0),interpolation='nearest',cmap='gray')

plt.show()

Fitting:98 points
Fitting:47 points


In [ ]:
[-0.09607926 -2.58486963 -0.7264244 ] [-0.09361351 -2.37996744 -0.57876109] 40 53

In [285]:
tia.translation_aling_pts(pfits1[:,1:4],pfits2[:,1:4],plt_val=True)

array([ 0.15995079,  2.59000803,  0.75762999])

In [267]:
dic_cor = pickle.load(open(r'D:\Bogdan\A549_SI13Ext_D_3_26_2018\Analysis5\Conv_zscan_21__current_cor_v2.pkl','rb'))
txyz2 =  pickle.load(open(r'D:\Bogdan\A549_SI13Ext_D_3_26_2018\Analysis4\Conv_zscan_21__current_cor.pkl','rb'))

In [219]:
dic_cor2 =  pickle.load(open(r'D:\Bogdan\A549_SI13Ext_D_3_26_2018\Analysis5\Conv_zscan_02__current_cor_v2.pkl','rb'))


In [268]:
np.round(np.mean(txyz2[:20],1)-[np.mean(txyz2[:20],1)[1]],2)

array([[ 0.14, -2.1 , -0.63],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.04, -0.72, -0.23],
       [ 0.1 , -0.41, -0.28],
       [ 0.03, -2.  , -0.12],
       [ 0.04, -1.47, -0.52],
       [ 0.03, -0.77, -0.52],
       [ 0.04, -0.84, -0.39],
       [ 0.12, -1.02,  0.06],
       [ 0.01,  0.03,  0.06],
       [-0.04, -0.59,  0.69],
       [ 0.13,  0.09,  1.16],
       [ 0.02, -0.36,  1.29],
       [ 0.21, -0.28,  1.27],
       [ 0.15, -0.96,  1.1 ],
       [ 0.05, -0.31,  1.21],
       [ 0.19,  0.18,  0.87],
       [ 0.19,  0.73,  1.19],
       [ 0.15,  0.  ,  0.82],
       [ 0.24, -0.7 ,  0.23]])

In [269]:
dic_cor2[ki[0]],txyz2[0]

(array([[-0.03192648,  0.00714669, -0.01393515],
        [ 0.03192648, -0.00714669,  0.01393515]]),
 [array([-0.26057639, -1.4498307 , -0.77176004]),
  array([-0.09492652, -1.27701033, -0.61995538])])

In [260]:
keys = dic_cor.keys()
keys2 = dic_cor2.keys()
ki = np.intersect1d(keys,keys2)
ki = np.array(ki)[np.argsort(map(get_hybe,ki))]
#[(k,np.mean(dic_cor[k],0)-np.mean(dic_cor2[k],0)) for k in ki]
np.round(np.array([np.mean(dic_cor2[k],0) for k in ki])-[np.mean(dic_cor2[ki[1]],0)],2)

array([[ 0.11,  1.65, -0.36],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.14,  0.76, -0.59],
       [ 0.  ,  1.06, -0.58],
       [ 0.06,  0.96, -0.95],
       [ 0.01,  1.43, -0.27],
       [ 0.21,  0.23, -0.92],
       [ 0.14,  0.06, -0.41],
       [ 0.04,  0.88, -0.68],
       [-0.05,  0.7 , -0.86],
       [ 0.12,  1.31, -0.78],
       [-0.08,  1.45, -0.66],
       [ 0.11,  1.2 , -1.  ],
       [ 0.15,  0.61, -1.19],
       [ 0.15,  0.84, -1.23],
       [ 0.09,  1.06, -1.11],
       [ 0.2 , -0.5 , -0.42],
       [ 0.08,  0.85, -1.06],
       [ 0.02,  2.16, -0.63],
       [ 0.02,  1.67, -1.23],
       [ 0.03,  1.2 , -0.74],
       [ 0.15,  2.75, -0.95],
       [ 0.01,  1.66, -0.79],
       [ 0.16,  1.24, -0.81],
       [ 0.1 ,  1.55, -0.61],
       [ 0.16,  1.52, -0.46],
       [ 0.13,  2.32, -0.41],
       [ 0.17,  1.34, -0.62],
       [ 0.2 ,  2.48, -0.55],
       [ 0.13,  1.24,  0.22],
       [ 0.19,  0.99,  0.33],
       [ 0.11,  2.33, -0.17],
       [ 0.07,  1.54, -0.56],
       [ 0

In [226]:
dic_cor['H1R9']

array([[-0.01757451,  0.05441316,  0.01411211],
       [ 0.01757451, -0.05441316, -0.01411211]])

In [255]:
dists = cdist(chr_pts_,centers)
mindist = np.min(dists,0)
keep = mindist<cutoff_window #keep only points within a distince cutoff_window from a chromosome
print dists.shape
centersh_close = centersh[keep] 

(41L, 271L)


In [140]:
reload(tia)
#tia.get_STD_centers(ims_beads[0],hseed=150,nseed=500,plt_val=True)
tia.get_STD_beaddrift(ims_beads[:3],sz_ex=75,hseed=100,nseed=100,ref=None,force=True)#,save_file=save_file)

Aligning 0
[-0.27847422 -5.60937106 -0.64613467] [-0.26486985 -5.58067618 -0.66107494]
Aligning 1
[ 0.  0.  0.] [ 0.  0.  0.]
Aligning 2
[-0.14559252  1.01004937  0.15957446] [-0.19759638  1.00774016  0.1864611 ]


([[array([-0.27847422, -5.60937106, -0.64613467]),
   array([-0.26486985, -5.58067618, -0.66107494])],
  [array([ 0.,  0.,  0.]), array([ 0.,  0.,  0.])],
  [array([-0.14559252,  1.01004937,  0.15957446]),
   array([-0.19759638,  1.00774016,  0.1864611 ])]],
 True)

In [127]:
reload(tia)

<module 'TadImagingAnalysis' from 'C:\Data\Alistair\code\python-functions\python-functions-library\TadImagingAnalysis.py'>

In [ ]:
cdist

In [23]:
plt.plot(x,y,'o')
plt.show()

In [28]:

candid_dic[tag]=np.array(self.pfits)#drif corrected
candid_spot[i_master]=(candid_dic,np.array(master[::-1]))
candid_dic[tag] =

57

In [14]:
len(ims_cy5)

1

In [ ]:
candid_spot[i_master]=(candid_dic,np.array(master[::-1]))

In [ ]:
#Power up the GUI and run across all fov and chroms selected
reload(tia)
overwrite=False
analysis_folder = master_folder+os.sep+r'Analysis1'
if not os.path.exists(analysis_folder):
    os.makedirs(analysis_folder)
folders_keep = folders
for ind in range(len(fov_ids)):
    try:
        plt.close('all')
        candid_spot = {}
        candid_spotS = {}

        fov_id = fov_ids[ind]
        fl_cands = analysis_folder+os.sep+fovs[fov_id].replace('.dax','__current_cand.pkl')#file where it save candidates
        fl_candsS = analysis_folder+os.sep+fovs[fov_id].replace('.dax','__current_candS.pkl')#file where it save candidates
        fl_finished = analysis_folder+os.sep+fovs[fov_id].replace('.dax','.finished')#file where it marks finished
        file_=fovs[fov_id]
        print file_
        if not os.path.exists(fl_finished) or overwrite:
            if os.path.exists(fl_cands) and not overwrite:
                candid_spot = pickle.load(open(fl_cands,'rb'))
            if os.path.exists(fl_candsS) and not overwrite:
                candid_spotS = pickle.load(open(fl_candsS,'rb'))
            ims_cy5,ims_beads,names=[],[],[]
            for folder in folders_keep:
                file__= folder+os.sep+file_
                if os.path.exists(file__):
                    print file__
                    names+=[os.path.basename(folder)]
                    im = tia.DaxReader(file__).loadMap()
                    ims_beads += [im[2::2][5:-5]/im_beads_repair*np.median(im_beads_repair)]
                    ims_cy5 += [im[1::2][5:-5]/im_cy5_repair*np.median(im_cy5_repair)]

            chroms = tia.imshow_mark_3d_v2(ims_cy5,image_names=names)

            chroms.width_z = 1.8*1.5/2.
            chroms.hot_pix_th=4

            from scipy.spatial.distance import cdist

            fov_id = fov_ids[ind]
            chr_pts_ = chr_pts[ind]

            self=chroms
            cutoff_trace=10
            dm =20#dimension of cube where to zoom in (actually 60 pix)
            ref=0
            #compute the drift
            save_file = analysis_folder+os.sep+fovs[fov_id].replace('.dax','__current_cor.pkl')
            txyz_both,overwrite = tia.get_STD_beaddrift(ims_beads,sz_ex=75,hseed=200,ref=None,force=False,save_file=save_file)
            if len(np.array(txyz_both).shape)==3:
                txyz = np.mean(txyz_both,1)
            else:
                txyz = txyz_both
            txyz = np.array(txyz)-[txyz[ref]]

            for i_master,master in enumerate(chr_pts_):
                if not candid_spot.has_key(i_master):
                    self.ax2.set_ylim(master[2]+dm+dm/2,master[2]-dm-dm/2)
                    class_ids_new,coords_new=[],[]
                    candid_dic={}#this gets saved to file
                    candid_dicS={}
                    #for each chr you have a candid_dic. the candid_dic dictionary goes across hybes and reports a list of fits
                    sel_cl_dic={}
                    sel_max_dic={}
                    for self.index_im in range(len(self.ims)):
                        self.set_image()
                        drift_x,drift_y,drift_z = txyz[self.index_im][::-1]
                        #drift_x,drift_y = int(drift_x),int(drift_y)
                        drift_x,drift_y = int(np.min([drift_x,2*self.ims[0].shape[-2]])),int(np.min([drift_y,2*self.ims[0].shape[-1]]))
                        self.ax1.set_xlim(master[0]+drift_x-dm,master[0]+drift_x+dm)#
                        self.ax1.set_ylim(master[1]+drift_y+dm,master[1]+drift_y-dm)#
                        self.auto_scale()
                        self.th_seed=250
                        self.get_seed_points()
                        self.fit_seed_points()
                        if len(self.pfits)==0:
                            self.th_seed=150
                            self.get_seed_points()
                            self.fit_seed_points()
                        ids=np.array(self.class_ids)
                        coords=np.array(self.coords)

                        if len(self.pfits)>0:
                            tag = os.path.basename(self.image_names[self.index_im])
                            candid_dic[tag]=np.array(self.pfits)
                            candid_dic[tag][:,1:4]=candid_dic[tag][:,1:4]-[txyz[self.index_im]]#apply drift correction

                            all_pts_hybe = candid_dic[tag][:,1:4]
                            chr_pts_comp =[pt__[::-1]for pt__ in chr_pts_]
                            inds = np.argmin(cdist(all_pts_hybe,chr_pts_comp),-1)
                            keep = inds==i_master
                            candid_dicS[tag] = np.array(candid_dic[tag])
                            candid_dic[tag] = candid_dic[tag][keep]

                            if np.sum(keep)>0:
                                coords_new.append(self.pfits[keep][0][1:4][::-1])
                                class_ids_new.append(self.index_im)
                            self.coords=coords_new
                            self.class_ids=class_ids_new
                            self.populate_draw_xyz()
                            self.set_image()
                    candid_spot[i_master]=(candid_dic,np.array(master[::-1]))
                    candid_spotS[i_master]=(candid_dic,np.array(master[::-1]))
                    pickle.dump(candid_spot,open(fl_cands,'wb'))
                    pickle.dump(candid_spotS,open(fl_candsS,'wb'))
            fid = open(fl_finished,'wb')
            fid.close()
    except:
        print "Failed"